spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/question_bank?useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource